name: Deploy to PROD (Production Site)

# Se ejecuta al hacer push a la rama 'main'
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_deploy_prod:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'

      - name: Install Dependencies
        run: |
          npm install
          cd functions && npm install && cd ..

      - name: Build Application for Production
        run: npm run build
        env:
          VITE_FIREBASE_API_KEY: ${{ secrets.VITE_FIREBASE_API_KEY_PROD }}
          VITE_FIREBASE_AUTH_DOMAIN: ${{ secrets.VITE_FIREBASE_AUTH_DOMAIN_PROD }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID_PROD }}
          VITE_FIREBASE_STORAGE_BUCKET: ${{ secrets.VITE_FIREBASE_STORAGE_BUCKET_PROD }}
          VITE_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.VITE_FIREBASE_MESSAGING_SENDER_ID_PROD }}
          VITE_FIREBASE_APP_ID: ${{ secrets.VITE_FIREBASE_APP_ID_PROD }}
          VITE_FIREBASE_MEASUREMENT_ID: ${{ secrets.VITE_FIREBASE_MEASUREMENT_ID_PROD }}
          VITE_GOOGLE_MAPS_API_KEY: ${{ secrets.VITE_GOOGLE_MAPS_API_KEY_PROD }}
          VITE_RECAPTCHA_SITE_KEY: ${{ secrets.VITE_RECAPTCHA_SITE_KEY_PROD }}
          VITE_ADD_PROVIDER_LEAD_FUNCTION_URL: ${{ secrets.VITE_ADD_PROVIDER_LEAD_FUNCTION_URL_PROD }}
          VITE_APP_MODE: "live"

      - name: Deploy to Firebase (PROD)
        run: |
          npx firebase-tools deploy --only hosting:${{ secrets.FIREBASE_HOSTING_SITE_PROD }},functions --project ${{ secrets.FIREBASE_PROJECT_ID_PROD }} --force
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}